# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 56e8180
_src_path: gh:vivienm/copier-rust
author_name: Vivien Maisonneuve
copyright_holder: Vivien Maisonneuve
copyright_year: 2023
github_account: vivienm
hosting_platform: github
license: MIT
package_name: namexif
project_description: Rename photos according to their EXIF date tag.
project_name: namexif
project_type: application
repo_name: namexif
rust_toolchain: stable
