# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 63e7058
_src_path: gh:vivienm/copier-rust
author_fullname: Vivien Maisonneuve
copyright_holder: Vivien Maisonneuve
copyright_license: MIT
copyright_year: 2023
package_name: namexif
pages_enabled: false
project_description: Rename photos according to their EXIF date tag.
project_name: namexif
project_type: bin
repository_hosted: true
repository_name: namexif
repository_namespace: vivienm
repository_provider: github.com
repository_url: https://github.com/vivienm/namexif
rust_toolchain: nightly
