image: registry.gitlab.com/vmaison/docker-ci-rust:latest

stages:
- lint
- test

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"

lint:
  stage: lint
  script:
  - cargo fmt -- --check
  - cargo clippy

test:
  stage: test
  script:
  - cargo check --verbose
  - cargo test --verbose
  cache:
    paths:
    - .cargo/
    - target/
