test:
  stage: test
  image: registry.gitlab.com/vmaison/docker-ci-rust:latest
  variables:
    CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  script:
  - cargo fmt -- --check
  - cargo clippy
  - cargo check --verbose
  - cargo test --verbose
  cache:
    paths:
    - .cargo/
    - target/

deploy:
  stage: deploy
  script:
  - curl -X POST -F "token=${TRIGGER_TOKEN}" -F "ref=${TRIGGER_REF_NAME}" "${TRIGGER_URL}"
  only:
  - master
