[package]
name = "namexif"
version = "0.1.0"
edition = "2021"
description = "Rename photos according to their EXIF date tag."
repository = "https://github.com/vivienm/namexif"
license = "MIT"
publish = false

[dependencies]
anyhow = "1.0.100"
chrono = { version = "0.4.42", default-features = false, features = ["std", "clock"] }
chrono-tz = "0.10.4"
clap = { version = "4.5.49", features = ["cargo", "derive", "env"] }
clap_complete = "4.5.59"
derive_more = { version = "2.0.1", features = ["display", "error", "from"] }
kamadak-exif = "0.6.1"
rayon = "1.11.0"
simplelog = "0.12.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

[build-dependencies]
chrono-tz = "0.10.4"
log = "0.4.28"
