[package]
name = "namexif"
version = "0.1.0"
authors = ["Vivien Maisonneuve <v.maisonneuve@gmail.com>"]
description = "Rename photos according to their EXIF date."
license = "MIT"
build = "build.rs"

[dependencies]
clap = "2.32.0"
chrono = "0.4"
chrono-tz = "0.5"
kamadak-exif = "0.3.1"
log = "0.4"
rayon = "1.0.2"
simplelog = "0.5.2"
derive_more = "0.13.0"

[build-dependencies]
clap = "2.32.0"
