name: "Continuous integration"

on:
  push:
  pull_request:

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  just:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "dtolnay/rust-toolchain@nightly"
      with:
        components: "clippy, rustfmt"
    - uses: "actions/cache@v3"
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          target/
        key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
        restore-keys: |
          ${{ runner.os }}-cargo-
    - run: "cargo install just cargo-deny typos-cli"
    - run: "just"
      env:
        RUSTFLAGS: "-D warnings"
        RUSTDOCFLAGS: "-D warnings"
    - uses: "actions/upload-artifact@v3"
      with:
        name: "doc"
        path: "./target/doc"
        retention-days: 7
