name: "CI"

on:
  push:
  pull_request:

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  just:
    name: "Just"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Install the Rust toolchain"
        uses: "dtolnay/rust-toolchain@stable"
        with:
          components: "clippy, rustfmt"
      - name: "Install sccache"
        uses: "mozilla-actions/sccache-action@v0.0.5"
      - name: "Set up sccache"
        run: |
          echo "RUSTC_WRAPPER=sccache" >> "${GITHUB_ENV}"
          echo "SCCACHE_GHA_ENABLED=true" >> "${GITHUB_ENV}"
      - name: "Install development tools"
        uses: "taiki-e/install-action@v2"
        with:
          tool: "just, cargo-audit, typos"
      - name: "Cache Cargo directories"
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/advisory-db/
            target/
          key: "${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml', 'Cargo.lock') }}"
          restore-keys: "${{ runner.os }}-cargo-"
      - name: "Run Just"
        run: "just ci"
        env:
          RUSTFLAGS: "-D warnings"
          RUSTDOCFLAGS: "-D warnings"
